[profile.default]
src = 'src'
test = 'test/'
out = 'out'
libs = ['lib']
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 1_000
via-ir = true
ffi = true
evm_version = "cancun"

[fmt]
line_length = 80
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
optimism = "${OPTIMISM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
baseGoerli = "${BASE_GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
optimismGoerli = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
baseGoerli = { key = "${BASESCAN_API_KEY}" }