name: coverage

on: [push]

env:
    FOUNDRY_PROFILE: default

jobs:
    check:
        strategy:
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: |
                  npm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Report Coverage
              run: |
                forge coverage --fork-url ${{ secrets.ARBITRUM_RPC_URL }} --etherscan-api-key ${{ secrets.ARBISCAN_API_KEY }} --report lcov --ir-minimum

            - name: Upload Coverage Report
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  files: ./lcov.info
                  name: codecov-unit
                  fail_ci_if_error: true
                  verbose: true
