name: test

on: [push]

env:
    FOUNDRY_PROFILE: default

jobs:
    check:
        strategy:
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: |
                  npm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Build Project
              run: |
                  forge --version
                  forge build
              id: build

            - name: Test Project
              run: |
                forge test --fork-url ${{ secrets.ARBITRUM_RPC_URL }} --etherscan-api-key ${{ secrets.ARBISCAN_API_KEY }} -vvv
              id: test